# Github workflow to compile latex and deploy the pdf to an orphan branch.
# The latest compiled pdf is made available at e.g.
# https://github.com/dgerosa/reponame/blob/build/filename.pdf
# Davide Gerosa (2021) https://github.com/dgerosa

name: writeapaper
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: |
            papers/hull_aspect_ratios/hull_aspect_ratios.tex
            papers/wec_as_multiport/wec_as_multiport.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: PDFs
          path: |
            papers/hull_aspect_ratios/hull_aspect_ratios.pdf
            papers/wec_as_multiport/wec_as_multiport.pdf
          compression-level: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          merge-multiple: true
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ GITHUB_WORKSPACE }}
          publish_branch: build
          force_orphan: true
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: build_latex
  #   steps:
  #     - env:
  #         OUTPUT1: ${{needs.build_latex.outputs.output1}}
  #       run: echo "Artifact ID from previous job is $OUTPUT1"
  # deploy:
  #   # Edit here if compiling multiple papers
  #   needs: [build_latex]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: actions/download-artifact@v4
  #       with:
  #         path: github_artifacts
  #     - name: move
  #       run: |
  #           mkdir -p github_deploy
  #           mv github_artifacts/*/* github_deploy
  #     - name: deploy on orphan branch
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./github_deploy
  #         publish_branch: build
  #         force_orphan: true
  # clean:
  #   needs: [deploy]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: delete
  #       uses: geekyeggo/delete-artifact@v2
  #       with:
  #         name: '*.pdf'